apps/user/urls.py
from django.urls import path
from . import views
from apps.user.views import *
from django.contrib.auth.decorators import login_required

app_name = 'Usuarios'

urlpatterns = [
    path('cliente/lista', lista.as_view(), name='lista_cliente'),
    path('cliente/reporte', report_cliente.as_view(), name='reporte_cliente'),
    path('cliente/nuevo', login_required(CrudView.as_view()), name='nuevo_cliente'),
    path('cliente/editar/<int:pk>', login_required(Updateview.as_view()), name='editar_cliente'),
    path('usuario/lista', lista_user.as_view(), name='lista_usuario'),
    path('usuario/reporte', report_user.as_view(), name='reporte_usuario'),
    path('usuario/nuevo', login_required(CrudView_user.as_view()), name='nuevo_usuario'),
    path('usuario/editar/<int:pk>', login_required(Updateview_user.as_view()), name='editar_usuario'),
    path('usuario/perfil', login_required(Profile.as_view()), name='perfil'),
    path('change_group/<int:pk>', login_required(UserChangeGroup.as_view()), name='user_change_group'),
    path('reset', views.ResetPass, name='Reset'),
    path('groups', login_required(Listgroupsview.as_view()), name='groups'),
    path('newgroup', login_required(CrudViewGroup.as_view()), name='newgroup'),
    path('grupo_editar/<int:pk>', login_required(UpdateGroup.as_view()), name='grupo_editar'),

    # path('profile', login_required(views.profile), name='profile'),

]

citas/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps import backEnd
from citas import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu', login_required(backEnd.menu), name='menu'),
    path('', login_required(backEnd.menu)),
    path('login', backEnd.logeo, name='login'),
    path('register', backEnd.cliente_add, name='register'),
    path('logout', login_required(backEnd.disconnect), name='logout'),
    path('connect/', backEnd.connect, name='connect'),
    path('verificar/', backEnd.check_ced, name='verificar'),
    path('equipos/', include('apps.maquina.urls', namespace='equipos')),
    path('categoria/', include('apps.categoria.urls', namespace='categoria')),
    path('presentacion/', include('apps.presentacion.urls', namespace='presentacion')),
    path('empleado/', include('apps.empleado.urls', namespace='empleado')),
    path('proveedor/', include('apps.proveedor.urls', namespace='proveedor')),
    path('producto/', include('apps.producto.urls', namespace='producto')),
    path('compra/', include('apps.compra.urls', namespace='compra')),
    path('transaccion/', include('apps.venta.urls', namespace='venta')),
    path('servicio/', include('apps.servicio.urls', namespace='servicio')),
    path('persona/', include('apps.user.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/front-end/group/group_form.html
{% extends 'front-end/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

    {#        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
    <link rel="stylesheet" href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}"/>
{% endblock %}
{% block content %}
    <!-- BASIC FORM ELELEMNTS -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5><i class="{{ icono }}"></i> {{ titulo }}</h5>
                </div>
                <div class="card-body">
                    <div class="form">
                        <form class="cmxform form-horizontal style-form" id="form" method="POST" action="{{ crud }}"
                              enctype="multipart/form-data">
                            {% csrf_token %}{{ form.media }}
                            <input type="hidden" id="action" name="action" value="{{ action }}">
                            <input type="hidden" name="option" value="{{ option }}">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            <div class="container-fluid">
                                <div class="form-group col-lg-12">
                                    {{ form.as_p }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="container-fluid">
                                    <table id="datatable"
                                           class="table table-striped table-bordered table-hover dataTable no-footer">
                                        <thead>
                                        <tr>
                                            <td>Modulo</td>
                                            <td>Ver</td>
                                            <td>Agregar</td>
                                            <td>Editar</td>
                                            <td>Eliminar</td>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for permiso in permisos %}
                                            <tr>
                                                <td>{% if permiso.model == 'group' %}
                                                PERFILES
                                                    {% elif permiso.model == 'user' %}
                                                    USUARIOS
                                                    {% else %}
                                                    {{ permiso.model|upper }}
                                                {% endif %} </td>
                                                <td><input type="checkbox" class="check_view" {% if permiso.view %} checked="checked"{% endif %} idp = "{{permiso.model }}"></td>
                                                <td>{% if not permiso.model == 'reportes' %}
                                                <input type="checkbox" class="check_add"{% if permiso.add %} checked="checked"{% endif %} idp = "{{permiso.model }}">
                                                {% endif %} </td>
                                                {% if permiso.model == 'venta' or permiso.model == 'compra' or permiso.model == 'reportes' %}
                                                    <td colspan="2"></td>
                                                {% else %}
                                                    <td><input type="checkbox" class="check_edit" {% if permiso.edit %} checked="checked"{% endif %}  idp = "{{permiso.model }}"></td>
                                                    <td><input type="checkbox" class="check_delete" {% if permiso.delete %} checked="checked"{% endif %} idp = "{{permiso.model }}"></td>
                                                {% endif %}
                                            </tr>
                                        {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-0 col-lg-12">
                                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> {{ boton }}
                                    </button>
                                    <button class="btn btn-danger" type="button" onclick="window.history.back();"><i
                                            class="fa fa-times"></i>
                                        Cancelar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <!-- /form-panel -->
        </div>
        <!-- /col-lg-12 -->
    </div>
    <!-- /row -->
{% endblock %}
{% block script %}
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>
    <script src="{% static 'apps/group/group.js' %}"></script>
    <script src="{% static 'apps/funtions.js' %}"></script>
    <script>
    $(document).ready(function () {
        $.each({{ permisos_select|safe }}, function (key, value) {
            permisos.add(value);
        })
    })
    </script>

{% endblock %}
{% block extra %}

{% endblock %}

templates/front-end/group/group_list.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block formulario %}

{% endblock %}
{% block table %}
    <thead>
    <tr>
        <th style="width: 5%">Id</th>
        <th style="width: 5%">Nombre</th>
        <th style="width: 80%">Permisos</th>
        <th style="width: 10%" class="text-center"><em class="fa fa-cog"></em></th>
    </tr>
    </thead>
    <tbody>

    </tbody>
{% endblock %}
{#{% block table_footer %}#}
{#    <a href="{% url 'user:newgroup' %}" type="button" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo Grupo</a>#}
{#    <button  type="button" class="btn btn-default" onclick="window.location.reload();"><i class="fas fa-sync-alt"></i> Actualizar</button>#}
{#{% endblock %}#}
{% block extra %}
    <script src="{% static 'apps/group/group_list.js' %}"></script>

{% endblock %}