apps/venta/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from apps.venta.views import *
from django.contrib.auth.decorators import login_required

app_name = 'Venta'

urlpatterns = [
    path('lista', login_required(lista.as_view()), name='lista'),
    path('venta/nuevo', login_required(CrudView.as_view()), name='nuevo'),
    path('cita/nuevo', login_required(CitacrudView.as_view()), name='cita_nuevo'),
    path('nuevo_online', login_required(CrudViewOnline.as_view()), name='nuevo_online'),
    path('online', views.CrudView_online, name='online'),
    path('chart', login_required(views.grap), name='chart'),
    path('printpdf/<int:pk>', login_required(printpdf.as_view()), name='printpdf'),
    path('printQR', login_required(printQR.as_view()), name='printQR'),
    path('venta/report_productos', login_required(report.as_view()), name='report_by_product'),
    path('venta/report_services', login_required(report_servicios.as_view()), name='report_by_services'),
    path('venta/report_empleado_venta', login_required(report_venta_empleado.as_view()), name='report_empleado_venta'),
    path('venta/report_total', login_required(report_total.as_view()), name='report_total'),
    path('report_total_pedidos', login_required(report_total_reserva.as_view()), name='report_total_pedidos'),
    path('data_tarjets', login_required(views.data_tarjets), name='data_tarjets'),

]

citas/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps import backEnd
from citas import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu', login_required(backEnd.menu), name='menu'),
    path('', login_required(backEnd.menu)),
    path('login', backEnd.logeo, name='login'),
    path('register', backEnd.cliente_add, name='register'),
    path('logout', login_required(backEnd.disconnect), name='logout'),
    path('connect/', backEnd.connect, name='connect'),
    path('verificar/', backEnd.check_ced, name='verificar'),
    path('equipos/', include('apps.maquina.urls', namespace='equipos')),
    path('categoria/', include('apps.categoria.urls', namespace='categoria')),
    path('presentacion/', include('apps.presentacion.urls', namespace='presentacion')),
    path('empleado/', include('apps.empleado.urls', namespace='empleado')),
    path('proveedor/', include('apps.proveedor.urls', namespace='proveedor')),
    path('producto/', include('apps.producto.urls', namespace='producto')),
    path('compra/', include('apps.compra.urls', namespace='compra')),
    path('transaccion/', include('apps.venta.urls', namespace='venta')),
    path('servicio/', include('apps.servicio.urls', namespace='servicio')),
    path('persona/', include('apps.user.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/venta/models.py
from datetime import datetime

from django.db import models
from django.forms import model_to_dict


from apps.compra.models import Detalle_compra
from apps.empleado.models import Empleado
from apps.maquina.models import Maquina
from apps.servicio.models import Servicio

from apps.producto.models import Producto
from apps.user.models import User
from apps.empresa.models import Empresa

estado = (
    (0, 'ANULADA'),
    (1, 'FINALIZADA'),
    (2, 'RESERVADA')
)


class Venta(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    empleado = models.ForeignKey(Empleado, on_delete=models.PROTECT, null=True, blank=True)
    fecha_factura = models.DateField(default=datetime.now)
    fecha_reserva = models.DateField(default=datetime.now)
    duracion_servicio = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    hora_inicio = models.IntegerField(default=0)
    minuto_inicio = models.IntegerField(default=0)
    hora_fin = models.IntegerField(default=0)
    minuto_fin = models.IntegerField(default=0)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    iva = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    estado = models.IntegerField(choices=estado, default=1)
    citacancelada = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s %s' % (self.user.get_full_name(), self.fecha_factura, self.total)

    def toJSON(self):
        item = model_to_dict(self)
        item['user'] = self.user.toJSON()
        item['estado_text'] = self.get_estado_display()
        item['fecha_factura'] = self.fecha_factura.strftime('%Y-%m-%d')
        item['fecha_reserva'] = self.fecha_reserva.strftime('%Y-%m-%d')
        item['duracion_servicio'] = format(self.duracion_servicio, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        item['iva'] = format(self.iva, '.2f')
        item['total'] = format(self.total, '.2f')
        return item

    def get_servicios(self):
        data = []
        for servicio in self.detalle_servicios_set.all():
            item = servicio.toJSON()
            data.append(item)
        return data

    class Meta:
        db_table = 'venta'
        verbose_name = 'venta'
        verbose_name_plural = 'ventas'


class Detalle_venta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.PROTECT)
    det_compra = models.ForeignKey(Detalle_compra, on_delete=models.PROTECT)
    pvp = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    cantidad = models.IntegerField(default=0)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return '%s' % self.venta

    def toJSON(self):
        empresa = Empresa.objects.first()
        item = model_to_dict(self)
        item['venta'] = self.venta.toJSON()
        item['det_compra'] = self.det_compra.toJSON()
        return item

    class Meta:
        db_table = 'detalle_venta'
        verbose_name = 'detalle_venta'
        verbose_name_plural = 'detalles_ventas'


class Detalle_servicios(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.PROTECT)
    empleado = models.ForeignKey(Empleado, on_delete=models.PROTECT)
    servicio = models.ForeignKey(Servicio, on_delete=models.PROTECT, null=True, blank=True, default=None)
    valor = models.DecimalField(default=1.00, max_digits=9, decimal_places=2, blank=True, null=True)
    cantidad = models.IntegerField(default=0)
    subtotals = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return '%s' % self.venta

    def toJSON(self):
        item = model_to_dict(self)
        item['venta'] = self.venta.toJSON()
        item['servicio'] = self.servicio.toJSON()
        item['empleado'] = self.empleado.toJSON()
        item['valor'] = format(self.valor, '.2f')
        item['subtotals'] = format(self.subtotals, '.2f')
        return item

    class Meta:
        db_table = 'detalle_venta_servicio'
        verbose_name = 'detalle_venta_servicio'
        verbose_name_plural = 'detalles_venta_servicios'


class Detalle_servicios_duracion(models.Model):
    detalle = models.ForeignKey(Detalle_servicios, on_delete=models.PROTECT)
    fecha_reserva = models.DateField(null=True, blank=True)
    hora_reserva = models.IntegerField(default=0)
    minuto_reserva = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % self.detalle

    def toJSON(self):
        item = model_to_dict(self)
        item['detalle'] = self.detalle.toJSON()
        item['fecha_reserva'] = self.fecha_reserva.strftime('%Y-%m-%d')
        return item

    class Meta:
        db_table = 'detalle_servicio_duracion'
        verbose_name = 'detalle_servicio_duracion'
        verbose_name_plural = 'detalle_servicio_duraciones'


class Detalle_maquinas(models.Model):
    servicio = models.ForeignKey(Detalle_servicios, on_delete=models.PROTECT)
    maquina = models.ForeignKey(Maquina, on_delete=models.PROTECT)

    def __str__(self):
        return '{}'.format(self.maquina.tipo.nombre)

    def toJSON(self):
        item = model_to_dict(self)
        item['maquina'] = self.maquina.toJSON()
        return item

    class Meta:
        db_table = 'detalle_venta_maquina'
        verbose_name = 'detalle_venta_maquina'
        verbose_name_plural = 'detalles_venta_maquina'

apps/venta/forms.py
from datetime import datetime

from django import forms

from .models import Venta, Detalle_servicios
from ..empleado.models import Empleado
from ..user.models import User


class VentaForm(forms.ModelForm):
    # constructor
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
            self.fields['fecha_factura'].widget.attrs = {
                'readonly': True,
                'class': 'form-control',
                'id': 'id_fecha_venta',
            }
            self.fields['fecha_reserva'].widget.attrs = {
                'class': 'form-control',
                'id': 'id_fecha_reserva',
                'autocomplete': 'off',
                'readonly': True
            }
            self.fields['duracion_servicio'].widget.attrs = {
                'class': 'form-control input-sm'
            }
            self.fields['fecha_factura'].initial = datetime.now().strftime('%Y-%m-%d')
            self.fields['fecha_reserva'].initial = ''
            self.fields['user'].widget.attrs = {'class': 'form-control'}
            self.fields['empleado'].widget.attrs = {'class': 'form-control'}
            self.fields['user'].queryset = User.objects.filter(tipo=0)
            self.fields['subtotal'].widget.attrs = {
                'value': '0.00',
                'class': 'form-control',
                'readonly': True
            }
            self.fields['iva'].widget.attrs = {
                'value': '0.00',
                'class': 'form-control',
                'readonly': True
            }
            self.fields['total'].widget.attrs = {
                'value': '0.00',
                'class': 'form-control',
                'readonly': True
            }

        # habilitar, desabilitar, y mas

    class Meta:
        model = Venta
        fields = [
            'fecha_factura',
            'fecha_reserva',
            'user',
            'empleado',
            'duracion_servicio',
            'subtotal',
            'iva',
            'total'
        ]
        labels = {
            'fecha_factura': 'Fecha de Venta',
            'fecha_reserva': 'Fecha',
            'user': 'Cliente',
            'empleado': 'Empleado',
            'duracion_servicio': 'Duracion de antencion',
            'subtotal': 'Subtotal',
            'iva': 'I.V.A.',
            'total': 'TOTAL'
        }
        widgets = {
            'fecha_factura': forms.DateInput(
                format='%Y-%m-%d',
                attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            ),
            'duracion_servicio ': forms.TextInput(),
        }


class Detalle_servicioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields['empleado'].widget.attrs = {'class': 'form-control', 'disabled': True}
            self.fields['empleado'].queryset = Empleado.objects.filter(estado=0)
            self.fields['servicio'].widget.attrs = {'class': 'form-control ct', 'multiple': 'multiple', 'placeholder_text_multiple': 'Selecciona uno o mas servicios....'}
            self.fields['servicio'].empty_label = None
        # habilitar, desabilitar, y mas
    class Meta:
        model = Detalle_servicios
        fields = [
            'empleado',
            'servicio'
        ]
        labels = {
            'empleado': 'Empleado',
            'servicio': 'Servicio'
        }
        widgets = {
            'servicio': forms.SelectMultiple()
        }

templates/front-end/venta/online.html
{% extends 'front-end/base.html' %}
{% load static %}
{% block head %}
    {% block form_head %}
        <!-- Latest compiled and minified CSS -->
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
        <link rel="stylesheet" href="{% static 'lib/bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}"/>
    {% endblock %}
{% endblock %}
{% block content %}
    <input type="hidden" id="action" name="action" value="{{ action }}">
    <input type="hidden" name="crud" value="{{ crud }}">
    <input type="hidden" name="crudserv" value="{{ crudserv }}">
    <input type="hidden" name="key" value="{{ key }}">
    <div class="card card-secondary">
        <div class="card-header">
            <h4> &nbsp;<i class="{{ icono }}"></i> {{ titulo }}</h4>
        </div>
        <div class="card-body">
            <div class="container col-lg-12">
                <div class="row">
                    <div class="col-lg-3 col-md-12">
                        <div class="card card-success">
                            <div class="card-header">
                                <h5>&nbsp;<i class="fa fa-book-open"></i> Datos de la Compra</h5>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_fecha_venta">{{ form.fecha_trans.label_tag }}</label>
                                    <div class="input-group">
                                        {{ form.fecha_trans }}
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="cliente"> Cliente:
                                        <br>
                                        <input type="text" name="cliente" class="form-control"
                                               value="{{ user.get_full_name }}" readonly="readonly">
                                    </label>
                                    <input type="hidden" value="{{ user.id }}" name="cliente_id">
                                </div>
                                <div class="form-group">
                                    <label for="id_subtotal">{{ form.subtotal.label_tag }}</label>
                                    <div class="input-group">
                                        {{ form.subtotal }}
                                        <div class="input-group-append">
                                            <span class="input-group-text">$</span>
                                        </div>
                                    </div>

                                </div>
                                <div class="form-group">
                                    <label for="id_iva">{{ form.iva.label_tag }}</label>
                                    <div class="input-group">
                                        {{ form.iva }}
                                        <div class="input-group-append">
                                            <span class="input-group-text">$</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_total">{{ form.total.label_tag }}</label>
                                    <div class="input-group">
                                        {{ form.total }}
                                        <div class="input-group-append">
                                            <span class="input-group-text">$</span>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-12">
                        <div class="card card-success">
                            <div class="card-header">
                                <h5><i class="fas fa-piggy-bank"></i>&nbsp;<strong>Compras</strong></h5>
                            </div>
                            <div class="card-body">
                                <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="venta-tab"
                                     id="venta">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5><i class="fas fa-piggy-bank"></i> Detalle de Productos</h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="form-group">
                                                    <label> Buscar Productos:</label>
                                                    <br>
                                                    {{ form2.inventario }}
                                                </div>
                                                <br>
                                            <div class="table-responsive">
                                                <table class="table" id="tblproductos">
                                                    <thead>
                                                    <tr>
                                                        <th><em class="fas fa-trash-alt"></em></th>
                                                        <th>Producto</th>
                                                        <th>Catg</th>
                                                        <th>Prest</th>
                                                        <th>Stock</th>
                                                        <th>Cant</th>
                                                        <th>Pvp</th>
                                                        <th>Subtotal</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>
                                                </table>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-12">


                        <button type="button" class="btn btn-danger btn-sm btn-flat"
                                onclick="cancel();">
                            <i class="fas fa-times"></i> Cancelar
                        </button>
                        <div id="paypal_btn" class="centrar" style="display: none">
                            <button type="submit" class="btn btn-primary btn-lg btn-flat" id="save">
                                <i class="far fa-save"></i> Reservar
                                <span class="ripple ripple-animate"
                                      style="height: 115px; width: 115px; animation-duration: 0.7s; animation-timing-function: linear; background: rgb(255, 255, 255); opacity: 0.4; top: -47.875px; left: -23.5px;"></span>
                            </button>
                            <hr>
                                <div id="paypal-button-container">

                                </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <style>
        #save {
            width: 37.5em;
            height: 3em;
        }

        .centrar {
            position: relative;
            left: 25%;
        }
    </style>
    <!-- Latest compiled and minified JavaScript -->
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script
            src="https://www.paypal.com/sdk/js?client-id=AQILMvtifA_65d48U-MTD4H-B8GUIkF5A4d0mt98W9N7reMHjVR4R4V286UHwf_JP08HwD6EOWEFQtWu"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
    </script>
    <script src="{% static 'apps/venta/venta_online_form.js' %}"></script>



{% endblock %}

templates/front-end/venta/report_product.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block formulario %}
{% endblock %}
{% block botones_head %}
    <div class="row">
        <div class="container-fluid">
            <div class="form-group">
                <a type="button" class="btn btn-white btn-danger" onclick="window.location.reload();"><span
                        class="glyphicon glyphicon-refresh"></span> Actualizar
                </a>
                <a type="button" class="btn btn-white btn-success" href="{% url 'venta:report_total' %}"><i
                        class="fa fa-money"></i> Totales
                </a>
                <a type="button" class="btn btn-white btn-default" href="{% url 'venta:report_by_services' %}"><i
                        class="fa fa-bullhorn"></i> Por Servicios
                </a>
                <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_empleado_venta'%}"><i
                        class="fa fa-users"></i> Por Empleado
                </a>
            </div>
            <div class="form-group col-lg-3">
                <label for="fecha"><strong>Filtar por Fecha:</strong></label>
                <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm">
            </div>
        </div>
    </div>
{% endblock %}
{% block table_content %}
    <thead>
    <tr>
        <th>Fecha</th>
        <th>Producto</th>
        <th>Categoria</th>
        <th>Presentacion</th>
        <th>Cantidad</th>
        <th>Pvp</th>
        <th>Subtotal</th>
        <th>Iva Generado</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th style="text-align:center" ><strong>Cantidad:</strong></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"><strong>Totales:</strong></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
    </tr>
    </tfoot>
{% endblock %}

{% block extra %}
    <script src="{% static 'apps/venta/report_product.js' %}"></script>
{% endblock %}
{% block javascript %}

{% endblock %}

templates/front-end/venta/report_services.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block formulario %}
{% endblock %}
{% block botones_head %}
    <div class="row">
        <div class="container-fluid">
            <div class="form-group">
                <a type="button" class="btn btn-white btn-danger" onclick="window.location.reload();"><span
                        class="glyphicon glyphicon-refresh"></span> Actualizar
                </a>
                <a type="button" class="btn btn-white btn-success" href="{% url 'venta:report_total' %}"><i
                        class="fa fa-money"></i> Totales
                </a>
                <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_by_product'%}"><i
                        class="fa fa-sort-numeric-desc"></i> Por Productos
                </a>
            </div>
            <div class="form-group col-lg-3">
                <label for="fecha"><strong>Filtar por Fecha:</strong></label>
                <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm">
            </div>
        </div>
    </div>
{% endblock %}
{% block table_content %}
    <thead>
    <tr>
        <th>Fecha</th>
        <th>Servicio</th>
        <th>Categoria</th>
        <th>Duracion</th>
        <th>Cantidad</th>
        <th>Valor</th>
        <th>Subtotal</th>
        <th>Iva Generado</th>
        <th>Total (con Iva)</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th style="text-align:center" ><strong>Cantidad:</strong></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"><strong>Totales:</strong></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
    </tr>
    </tfoot>
{% endblock %}

{% block extra %}
    <script src="{% static 'apps/venta/report_product.js' %}"></script>
{% endblock %}
{% block javascript %}

{% endblock %}

templates/front-end/venta/report_total.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block formulario %}

{% endblock %}
{% block botones_head %}
    <div class="row">
        <div class="container-fluid">
            <div class="form-group">
                <a type="button" class="btn btn-white btn-danger" onclick="window.location.reload();"><span
                        class="glyphicon glyphicon-refresh"></span> Actualizar
                </a>
                <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_by_product' %}"><i
                        class="fa fa-sort-numeric-desc"></i> Por Productos
                </a>
                <a type="button" class="btn btn-white btn-default" href="{% url 'venta:report_by_services' %}"><i
                        class="fa fa-bullhorn"></i> Por Servicios
                </a>
                 <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_empleado_venta'%}"><i
                        class="fa fa-users"></i> Por Empleado
                </a>
            </div>
            <div class="form-group col-lg-3">
                <label for="fecha"><strong>Filtar por Fecha:</strong></label>
                <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm">
            </div>
        </div>
    </div>
{% endblock %}
{% block elements %}
    <br>
    <div class="row">
        <div class="col-lg-4">
            <label for="fecha"><strong>Rango de Fechas:</strong></label>
            <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm"></div>
    </div>
    <br>
{% endblock %}
{% block table_content %}
    <thead>
    <tr>
        <th>Fecha</th>
        <th>Cliente</th>
        <th>Total (sin Iva)</th>
        <th>Total (Iva)</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th><strong>Totales: Esta pagina (Total filtrado)</strong></th>
        <th></th>
        <th></th>
        <th></th>

    </tr>
    </tfoot>
{% endblock %}
{% block extra %}
    <script src="{% static 'apps/venta/report_total.js' %}"></script>
{% endblock %}

templates/front-end/venta/report_total_reserva.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block elements %}
    <br>
        <div class="row">
        <div class="col-lg-4">
            <label for="fecha"><strong>Rango de Fechas:</strong></label>
            <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm"></div>
        </div>
    <br>
{% endblock %}
{% block table %}
    <thead>
    <tr>
        <th>Fecha</th>
        <th>Cliente</th>
        <th>Total (sin Iva)</th>
        <th>Total (Iva)</th>
        <th>Total (con Iva)</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th><strong>Totales:  Esta pagina (Total filtrado)</strong></th>
        <th></th>
        <th></th>
        <th></th>

    </tr>
    </tfoot>
{% endblock %}
{% block table_footer %}
    <a type="button" class="btn btn-success btn-sm" style="color: white" id="reload" onclick=" location.reload();">
        <i class="fas fa-sync-alt"></i> Actualizar
    </a>
{% endblock %}
{% block extra %}
    <script src="{% static 'apps/venta/report_total_reserva.js' %}"></script>
{% endblock %}

templates/front-end/venta/report_venta_empleado.html
{% extends 'front-end/list.html' %}
{% load static %}
{% block formulario %}
{% endblock %}
{% block botones_head %}
    <div class="row">
        <div class="container-fluid">
            <div class="form-group">
                <a type="button" class="btn btn-white btn-danger" onclick="window.location.reload();"><span
                        class="glyphicon glyphicon-refresh"></span> Actualizar
                </a>
                <a type="button" class="btn btn-white btn-success" href="{% url 'venta:report_total' %}"><i
                        class="fa fa-money"></i> Totales
                </a>
                <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_by_product'%}"><i
                        class="fa fa-sort-numeric-desc"></i> Por Productos
                </a>
                <a type="button" class="btn btn-white btn-primary" href="{% url 'venta:report_by_services'%}"><i
                        class="fa fa-bullhorn"></i> Por Servicios
                </a>
            </div>
            <div class="form-group col-lg-3">
                <label for="fecha"><strong>Filtar por Fecha:</strong></label>
                <input type="text" name="fecha" id="fecha" class="form-control form-control-sm input-sm">
            </div>
        </div>
    </div>
{% endblock %}
{% block table_content %}
    <thead>
    <tr>
        <th>Fecha</th>
        <th>Empleado</th>
        <th>Cliente</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
        <th>Iva Generado</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <tr>
        <th></th>
        <th></th>
        <th style="text-align:center" ><strong>Cantidad:</strong></th>
        <th style="text-align:center"><strong>Totales:</strong></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
        <th style="text-align:center"></th>
    </tr>
    </tfoot>
{% endblock %}

{% block extra %}
    <script src="{% static 'apps/venta/report_venta_empelado.js' %}"></script>
{% endblock %}
{% block javascript %}

{% endblock %}